---
add: ADD
after: AFTER
all: ALL
alter: ALTER
any: ANY
as: AS
asc: ASC
auto_increment: AUTO_INCREMENT
avg: AVG
before: BEFORE
begin: BEGIN
between: BETWEEN
bigint: BIGINT
bit_and: BIT_AND
bit_or: BIT_OR
bit_xor: BIT_XOR
blob: BLOB
by: BY
cascade: CASCADE
case: CASE
cast: CAST
chain: CHAIN
change: CHANGE
character: CHARACTER
char: CHAR
charset: CHARSET
close: CLOSE
collate: COLLATE
column: COLUMN
commit: COMMIT
consistent: CONSISTENT
constraint: CONSTRAINT
convert: CONVERT
count: COUNT
create: CREATE
cross: CROSS
cube: CUBE
date: DATE
datetime: DATETIME
decimal: DECIMAL
declare: DECLARE
default: DEFAULT
delayed: DELAYED
delete: DELETE
desc: DESC
distinct: DISTINCT
do: DO
drop: DROP
dual: DUAL
duplicate: DUPLICATE
each: EACH
else: ELSE
elseif: ELSEIF
end: END
engine: ENGINE
escape: ESCAPE
exists: EXISTS
'false': 'FALSE'
fetch: FETCH
first: FIRST
float: FLOAT
force: FORCE
for: FOR
from: FROM
global: GLOBAL
group: GROUP
having: HAVING
high_priority: HIGH_PRIORITY
if: IF
ignore: IGNORE
index: INDEX
in: IN
inner: INNER
insert: INSERT
integer: INTEGER
int: INT
into: INTO
is: IS
iterate: ITERATE
join: JOIN
key: KEY
leave: LEAVE
left: LEFT
like: LIKE
limit: LIMIT
lock: LOCK
longblob: LONGBLOB
longtext: LONGTEXT
loop: LOOP
low_priority: LOW_PRIORITY
max: MAX
mediumblob: MEDIUMBLOB
mediumint: MEDIUMINT
mediumtext: MEDIUMTEXT
min: MIN
mode: MODE
modify: MODIFY
natural: NATURAL
next: NEXT
'no': 'NO'
not: NOT
'null': 'NULL'
numeric: NUMERIC
offset: OFFSET
'on': 'ON'
open: OPEN
optimize: OPTIMIZE
order: ORDER
outer: OUTER
primary: PRIMARY
quick: QUICK
regexp: REGEXP
release: RELEASE
rename: RENAME
repeat: REPEAT
replace: REPLACE
restrict: RESTRICT
return: RETURN
right: RIGHT
rollback: ROLLBACK
rollup: ROLLUP
row: ROW
select: SELECT
session: SESSION
set: SET
share: SHARE
signed: SIGNED
smallint: SMALLINT
snapshot: SNAPSHOT
some: SOME
sounds: SOUNDS
start: START
sum: SUM
table: TABLE
temporary: TEMPORARY
text: TEXT
then: THEN
timestamp: TIMESTAMP
time: TIME
tinyblob: TINYBLOB
tinyint: TINYINT
tinytext: TINYTEXT
to: TO
transaction: TRANSACTION
trigger: TRIGGER
'true': 'TRUE'
union: UNION
unique: UNIQUE
unknown: UNKNOWN
unsigned: UNSIGNED
until: UNTIL
update: UPDATE
use: USE
using: USING
values: VALUES
value: VALUE
varchar: VARCHAR
view: VIEW
when: WHEN
where: WHERE
while: WHILE
with: WITH
work: WORK
xor: XOR
